<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jint" Version="4.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.3" />
    <PackageReference Include="PySharp.Interpreter" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TheFlowThing.Abstractions\TheFlowThing.Abstractions.csproj" />
    <ProjectReference Include="..\TheIoTThing.Abstractions\TheIoTThing.Abstractions.csproj" />
  </ItemGroup>

</Project>
